name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Set tag var
      id: vars
      run: echo ::set-output name=docker_tag::$(date +%s)
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag phires/php7-fpm:${{ steps.vars.outputs.docker_tag }}
    - name: Push the tagged Docker image
      run: docker push phires/php7-fpm:${{ steps.vars.outputs.docker_tag }}
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag phires/php7-fpm:latest
    - name: Push the latest Docker image
      run: docker push phires/php7-fpm:latest
